# Generated by Django 4.2.4 on 2023-08-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_days', models.PositiveIntegerField()),
                ('num_adults', models.PositiveIntegerField()),
                ('num_children', models.PositiveIntegerField()),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.bookingtype')),
            ],
        ),
    ]
